language: bash
services: docker

env:
#VERSIONS
  - VERSION=1.39.0 VARIANT=stretch-minimal
  - VERSION=1.39.0 VARIANT=stretch-minimal/slim
  - VERSION=1.39.0 VARIANT=stretch-default
  - VERSION=1.39.0 VARIANT=stretch-default/slim
  - VERSION=1.39.0 VARIANT=stretch-full
  - VERSION=1.39.0 VARIANT=stretch-full/slim
  - VERSION=1.39.0 VARIANT=buster-minimal
  - VERSION=1.39.0 VARIANT=buster-minimal/slim
  - VERSION=1.39.0 VARIANT=buster-default
  - VERSION=1.39.0 VARIANT=buster-default/slim
  - VERSION=1.39.0 VARIANT=buster-full
  - VERSION=1.39.0 VARIANT=buster-full/slim
  - VERSION=1.39.0 VARIANT=alpine3.10-minimal
  - VERSION=1.39.0 VARIANT=alpine3.10-default
  - VERSION=1.39.0 VARIANT=alpine3.10-full
#VERSIONS

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="rust:${VERSION}-${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
